{
 "title": "Análisis de la temperatura media en Navarra",
 "time": { "from": "2003-12-31T23:00:00.000Z", "to": "2018-12-31T23:00:00.000Z" },
 "panels": [
  {
   "title": "Temperatura media por semana",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Temperatura media por semana\"\nfrom Hechos\ngroup by YEAR(Hechos.fecha),WEEK(Hechos.fecha)\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Zona Pirineo\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Zona Pirineo\"\ngroup by YEAR(Hechos.fecha),WEEK(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Temp Tierra Estella por semana\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Tierra Estella\"\ngroup by YEAR(Hechos.fecha),WEEK(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Zona Noroeste\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Zona Noroeste\"\ngroup by YEAR(Hechos.fecha),WEEK(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Pamplona\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Pamplona\"\ngroup by YEAR(Hechos.fecha),WEEK(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Navarra Media Oriental\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Navarra Media Oriental\"\ngroup by YEAR(Hechos.fecha),WEEK(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Ribera Alta\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Ribera Alta\"\ngroup by YEAR(Hechos.fecha),WEEK(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Tudela\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Tudela\"\ngroup by YEAR(Hechos.fecha),WEEK(Hechos.fecha),Lugar.comarca\n"
    }
   ]
  },
  {
   "title": "Tempreatura media por año",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Temperatura media por año\"\nfrom Hechos\ngroup by YEAR(Hechos.fecha)\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Zona Pirineo\"\nfrom Hechos,Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Zona Pirineo\"\ngroup by YEAR(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Tierra Estella\"\nfrom Hechos,Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Tierra Estella\"\ngroup by YEAR(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Zona Noroeste\"\nfrom Hechos,Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Zona Noroeste\"\ngroup by YEAR(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Pamplona\"\nfrom Hechos,Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Pamplona\"\ngroup by YEAR(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Navarra Media Oriental\"\nfrom Hechos,Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Navarra Media Oriental\"\ngroup by YEAR(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Ribera Alta\"\nfrom Hechos,Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Ribera Alta\"\ngroup by YEAR(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Tudela\"\nfrom Hechos,Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Tudela\"\ngroup by YEAR(Hechos.fecha),Lugar.comarca\n"
    }
   ]
  },
  {
   "title": "Temperatura media por mes",
   "type": "graph",
   "description": "Cada barra representa un mes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Temperatura media por mes\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion\ngroup by YEAR(Hechos.fecha),MONTH(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Zona Pirineo\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Zona Pirineo\"\ngroup by YEAR(Hechos.fecha),MONTH(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Tierra Estella\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Tierra Estella\"\ngroup by YEAR(Hechos.fecha),MONTH(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Zona Noroeste\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Zona Noroeste\"\ngroup by YEAR(Hechos.fecha),MONTH(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Pamplona\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Pamplona\"\ngroup by YEAR(Hechos.fecha),MONTH(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Navarra Media Oriental\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Navarra Media Oriental\"\ngroup by YEAR(Hechos.fecha),MONTH(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Ribera Alta\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Ribera Alta\"\ngroup by YEAR(Hechos.fecha),MONTH(Hechos.fecha),Lugar.comarca\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Tudela\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Tudela\"\ngroup by YEAR(Hechos.fecha),MONTH(Hechos.fecha),Lugar.comarca\n"
    }
   ]
  },
  {
   "title": "Temperatura media por día",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  fecha as \"time\",\n  avg(temp_media) as \"Temperatura Media Navarra\"\nFROM Hechos\nGroUP BY fecha\n  \n\n"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Temp Zona Pirineo\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Zona Pirineo\"\ngroup by Lugar.comarca,Hechos.fecha"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Temp Tierra Estella\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Tierra Estella\"\ngroup by Lugar.comarca,Hechos.fecha"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Temp Zona Noroeste\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Zona Noroeste\"\ngroup by Lugar.comarca,Hechos.fecha"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Temp Pamplona\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Pamplona\"\ngroup by Lugar.comarca,Hechos.fecha"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Temp Navarra Media Oriental\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Navarra Media Oriental\"\ngroup by Lugar.comarca,Hechos.fecha"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Temp Ribera Alta\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Ribera Alta\"\ngroup by Lugar.comarca,Hechos.fecha"
    },
    {
     "rawSql": "select\n  Hechos.fecha as \"time\",\n  avg(Hechos.temp_media) as \"Temp Tudela\"\nfrom Hechos, Lugar\nwhere Hechos.estacion = Lugar.estacion and Lugar.comarca = \"Tudela\"\ngroup by Lugar.comarca,Hechos.fecha"
    }
   ]
  }
 ]
}